Repository zscaler/terraform-provider-zia, pull requests merged in 2023-03, with the labels that each got.

#196 (fix) traffic_forwarding_gre_tunnel and docs
  CHANGELOG.md
  GNUmakefile
  docs/data-sources/zia_traffic_forwarding_gre_vip_recommended_list.md
  docs/guides/release-notes.md
  docs/index.md
  docs/resources/zia_traffic_forwarding_gre_tunnel.md
  examples/zia_traffic_forwarding_gre_demo/provider.tf
  examples/zia_traffic_forwarding_gre_demo/zia_location_management.tf
  examples/zia_traffic_forwarding_gre_demo/zia_traffic_forwarding_gre_tunnels_numbered.tf
  examples/zia_traffic_forwarding_gre_demo/zia_traffic_forwarding_static_ips.tf
  examples/zia_traffic_forwarding_gre_tunnel/zia_traffic_forwarding_gre_tunnels_numbered.tf
  examples/zia_traffic_forwarding_gre_tunnel/zia_traffic_forwarding_gre_tunnels_unnumbered.tf
  examples/zia_traffic_forwarding_public_node_vips/README.md
  examples/zia_traffic_forwarding_public_node_vips/datasource.tf
  examples/zia_traffic_forwarding_recommended_vips/datasource.tf.tf
  go.mod
  go.sum
  zia/common/resourcetype/resource_type.go
  zia/common/testing/variable/variable.go
  zia/data_source_zia_location_management_test.go
  zia/data_source_zia_traffic_forwarding_gre_tunnels_test.go
  zia/data_source_zia_traffic_forwarding_gre_vip_recommended_list.go
  zia/data_source_zia_traffic_forwarding_static_ips_test.go
  zia/data_source_zia_traffic_forwarding_vpn_credentials_test.go
  zia/resource_zia_location_management.go
  zia/resource_zia_location_management_test.go
  zia/resource_zia_traffic_forwarding_gre_tunnels.go
  zia/resource_zia_traffic_forwarding_gre_tunnels_test.go
  zia/resource_zia_traffic_forwarding_static_ips_test.go
  zia/resource_zia_traffic_forwarding_vpn_credentials_test.go
Labels: bug

#194 try fix reorder
  .github/workflows/ci.yml
  GNUmakefile
  zia/common.go
  zia/resource_zia_firewall_filtering_rules.go
  zia/resource_zia_url_filtering_rules.go
Labels: bug

#201 fix dlp rules id issue
  zia/resource_zia_dlp_web_rules.go
Labels: bug

#206 (fix) Added validation to enforce string length
  CHANGELOG.md
  GNUmakefile
  docs/guides/release-notes.md
  examples/zia_dlp_notification_templates/basic.tf
  go.mod
  go.sum
  zia/common/resourcetype/resource_type.go
  zia/common/testing/variable/variable.go
  zia/data_source_zia_dlp_notification_templates.go
  zia/data_source_zia_dlp_notification_templates_test.go
  zia/resource_zia_dlp_dictionaries.go
  zia/resource_zia_dlp_notification_templates.go
  zia/resource_zia_dlp_notification_templates_test.go
  zia/resource_zia_dlp_web_rules.go
  zia/resource_zia_firewall_filtering_rules.go
  zia/resource_zia_fw_filtering_ip_destination_groups.go
  zia/resource_zia_fw_filtering_ip_source_groups.go
  zia/resource_zia_fw_filtering_network_application_groups.go
  zia/resource_zia_fw_filtering_network_services.go
  zia/resource_zia_fw_filtering_network_services_groups.go
  zia/resource_zia_location_management.go
  zia/resource_zia_rule_labels.go
  zia/resource_zia_traffic_forwarding_gre_tunnels.go
  zia/resource_zia_url_categories.go
  zia/resource_zia_url_filtering_rules.go
  zia/resource_zia_user_management_users.go
Labels: bug

#202 (feat) Location Basic Auth and User Auth Methods …
  docs/data-sources/zia_user_management.md
  docs/resources/zia_user_management.md
  examples/zia_user_management/zia_user_management_data/basic.tf
  version
  zia/data_source_zia_location_management.go
  zia/data_source_zia_user_management_users.go
  zia/provider.go
  zia/resource_zia_location_management.go
  zia/resource_zia_user_management_users.go
Labels: enhancement

#212 (fix) User Management group flattening function
  CHANGELOG.md
  docs/guides/release-notes.md
  go.mod
  go.sum
  zia/common.go
  zia/data_source_zia_user_management_users.go
Labels: bug

#214 (fix) Traffic Forwarding GRE Tunnel Error
  go.sum
  zia/data_source_zia_traffic_forwarding_gre_vip_recommended_list.go
  zia/resource_zia_traffic_forwarding_gre_tunnels.go
Labels: bug

#217 (fix) DLP Engine Resource SearchByName
  CHANGELOG.md
  docs/guides/release-notes.md
  go.mod
  go.sum
  zia/data_source_zia_dlp_engines.go
  zia/data_source_zia_dlp_engines_test.go
Labels: bug, enhancement
