Repository zscaler/terraform-provider-zia, pull requests merged in 2023-04, with the labels that each got.

#220 (Fix)Updated to zscaler-sdk-go v1.4.0
  CHANGELOG.md
  docs/guides/release-notes.md
  go.mod
  go.sum
Labels: bug, enhancement

#224 (Fix)Reduced NewTicker timer for faster rule processing
  CHANGELOG.md
  GNUmakefile
  docs/guides/release-notes.md
  docs/resources/zia_dlp_web_rules.md
  examples/zia_dlp_web_rules/basic.tf
  zia/common.go
  zia/data_source_zia_dlp_web_rules.go
Labels: bug, enhancement

#219 (Fix): DLP Rule Drift Issues
  CHANGELOG.md
  docs/data-sources/zia_dlp_web_rules.md
  docs/resources/zia_dlp_web_rules.md
  examples/zia_dlp_web_rules/basic.tf
  zia/common.go
  zia/data_source_zia_dlp_web_rules.go
  zia/resource_zia_dlp_web_rules.go
  zia/resource_zia_dlp_web_rules_test.go
Labels: bug

#227 Fetch specific sub-location of a location by name
  CHANGELOG.md
  docs/data-sources/zia_sub_location_management.md
  docs/guides/release-notes.md
  examples/zia_sub_location_management/datasource.tf
  zia/data_source_zia_location_management.go
Labels: enhancement
